services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=projeto
      - POSTGRES_DB=projeto
    volumes:
      - pools_pg_data:/bitnami/postgresql


volumes:
  pools_pg_data: